package com.alfonzjanfrithz.learn

fun sumOfEvenFibonnacciNumber(numOfFibonacciElements: Int): Int {
    return getFibonacciList(numOfFibonacciElements).filter { it % 2 == 0 }.sum()
}

/**
 * The next number is generated by adding the previous two number
 */
fun getFibonacciList(numOfFibonacci: Int): List<Int> {
    var listOfFibonacci = mutableListOf<Int>(1, 2)
    for (idx in 1..numOfFibonacci - 2) { // the first two elements will always 1 and 2
        listOfFibonacci.add(listOfFibonacci.takeLast(2).sum())
    }

    println("list of Fibonacci elements: $listOfFibonacci")
    return listOfFibonacci
}